CREATE PROCEDURE AZ.PagesCommentApprovalStateUpd(
	@VCode BIGINT,
	@ApprovalStateVCode SMALLINT
)
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY

		UPDATE AZ.PagesComment SET ApprovalStateVCode = @ApprovalStateVCode ,LastModifiedDate = GETDATE() WHERE VCode = @VCode
		
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrNo INT,@ErrMsg NVARCHAR(4000),@ErrSev INT,@ErrStt INT
		SELECT @ErrMsg = '(' + CONVERT(NVARCHAR(4000),ERROR_NUMBER()) + ') ' + ERROR_MESSAGE(),@ErrSev = ERROR_SEVERITY(),@ErrStt = ERROR_STATE()
		IF @@TRANCOUNT > 0 ROLLBACK TRAN
		RAISERROR(@ErrMsg,@ErrSev,@ErrStt)
	END CATCH
END
GO

