CREATE TABLE [AZ].[Gallery]
(
	[id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY, 
    [name] NCHAR(50) NULL, 
    [order] SMALLINT NOT NULL DEFAULT 0, 
    [image] NVARCHAR(50) NOT NULL,
    [productID] NVARCHAR(50) NOT NULL,
    [createDate] DATE DEFAULT(GETDATE()) NOT NULL,
    [lastModifiedDate] DATE DEFAULT(GETDATE()) NOT NULL,
)