CREATE TABLE [AZ].[ProductProperty]
(
	[id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY, 
    [value] NCHAR(50) NULL, 
    [productID] UNIQUEIDENTIFIER NOT NULL,
    [propertyID] UNIQUEIDENTIFIER NOT NULL,
    [createDate] DATE DEFAULT(GETDATE()) NOT NULL,
    [lastModifiedDate] DATE DEFAULT(GETDATE()) NOT NULL,
)
