CREATE TABLE [AZ].[SMSLogType](
	[VCode] [smallint] NOT NULL,
	[Code] [smallint] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SMSLogType] PRIMARY KEY CLUSTERED 
(
	[VCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


