CREATE TABLE [AZ].[SMSType] (
    [VCode]    SMALLINT      NOT NULL,
    [Name]     NVARCHAR (50) NOT NULL,
    [EnumName] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SMSType] PRIMARY KEY CLUSTERED ([VCode] ASC)
);
GO