CREATE PROCEDURE [AZ].[Backup_ICE]
AS
BEGIN
	DECLARE @var NVARCHAR(max) ='D:\Backups\ICE_' + REPLACE(RTRIM(CONVERT(CHAR,GETDATE())), ':',',')+'.bak';
	BACKUP DATABASE ICE TO DISK = @var WITH COMPRESSION

	DECLARE @var98 NVARCHAR(max) ='\\192.168.3.1\BackUps\Transactions\ICE_' + REPLACE(RTRIM(CONVERT(CHAR,GETDATE())), ':',',')+'.bak';
    BACKUP DATABASE ICE TO DISK = @var98 WITH COMPRESSION
END