CREATE PROCEDURE [AZ].[SetSetting](
@Key VARCHAR(100),
@SubSystemVCode INT,
@NewValue AS NVARCHAR(MAX)
)
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY

		IF EXISTS(SELECT 1 FROM AZ.ApplicationSetting WHERE [Key] = @Key)
		BEGIN
			UPDATE AZ.ApplicationSetting SET [Value] =  @NewValue WHERE [Key] = @Key 
		END
	COMMIT TRAN
	END TRY
		BEGIN CATCH
		DECLARE @ErrNo INT,@ErrMsg NVARCHAR(4000),@ErrSev INT,@ErrStt INT
		SELECT @ErrMsg = '(' + CONVERT(NVARCHAR(4000),ERROR_NUMBER()) + ') ' + ERROR_MESSAGE(),@ErrSev = ERROR_SEVERITY(),@ErrStt = ERROR_STATE()
		IF @@TRANCOUNT > 0 ROLLBACK TRAN
		RAISERROR(@ErrMsg,@ErrSev,@ErrStt)
	END CATCH
END