CREATE PROCEDURE [AZ].[CheckKycUpd](
	@UserVCode		BIGINT,
	@KycVCode	BIGINT,
	@IsValid		BIT
)
AS
BEGIN
	BEGIN TRY
		UPDATE AZ.Kyc SET IsValid = @IsValid WHERE VCode = @KycVCode
	END TRY
		BEGIN CATCH
		DECLARE @ErrNo INT,@ErrMsg NVARCHAR(4000),@ErrSev INT,@ErrStt INT
		SELECT @ErrMsg = '(' + CONVERT(NVARCHAR(4000),ERROR_NUMBER()) + ') ' + ERROR_MESSAGE(),@ErrSev = ERROR_SEVERITY(),@ErrStt = ERROR_STATE()
		IF @@TRANCOUNT > 0 ROLLBACK TRAN
		RAISERROR(@ErrMsg,@ErrSev,@ErrStt)
	END CATCH
END