CREATE PROCEDURE [AZ].[GetUserLastSevenHours](
	@UserVCode BIGINT
)
AS
BEGIN
	SELECT * INTO #T FROM AZ.Identification (NOLOCK) WHERE UserVCode = @UserVCode AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,0,GETDATE()) AS DATE)

	SELECT 
		DATEPART(HOUR,GETDATE()) [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = DATEPART(HOUR,GETDATE())
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 1 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 1 END
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 2 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 2 END
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 3 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt 
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 3 END
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 4 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 4 END
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 5 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate) = CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 5 END
	UNION
	SELECT 
		CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 6 END [HOUR],
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (4,13) THEN 1 ELSE 0 END),0) ConfirmedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (7,14,15) THEN 1 ELSE 0 END),0) RejectedCnt, 
		ISNULL(SUM(CASE WHEN IdentificationStateVCode IN (17,11,18) THEN 1 ELSE 0 END),0) WaitingPersonConfirmationCnt
	FROM #T
	WHERE DATEPART(HOUR,EntryDate)= CASE WHEN DATEPART(HOUR,GETDATE()) = 0 THEN 23 ELSE DATEPART(HOUR,GETDATE()) - 6 END

	DROP TABLE #T
END