CREATE PROCEDURE [AZ].[GetUserLastSevenDaysSeen](
	@UserVCode BIGINT
)
AS
BEGIN
	SELECT * INTO #T FROM AZ.Identification (NOLOCK) WHERE UserVCode = @UserVCode

	SELECT CAST(DATEADD(DAY,0,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,0,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-1,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-1,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-2,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-2,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-3,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-3,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-4,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-4,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-5,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-5,GETDATE()) AS DATE)
	UNION
	SELECT CAST(DATEADD(DAY,-6,GETDATE()) AS DATE) [ReportDate],COUNT(1) cnt FROM #T 
		WHERE IdentificationStateVCode = 4 AND CAST(EntryDate AS DATE) = CAST(DATEADD(DAY,-6,GETDATE()) AS DATE)

	DROP TABLE #T
END