CREATE PROCEDURE [AZ].[IdentificationRateUpd](
	@IdentificationVCode BIGINT,
	@Rate DECIMAL(5,2)
)
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY
		UPDATE AZ.Identification SET [Rate] = @Rate WHERE VCode = @IdentificationVCode

		COMMIT TRAN
	END TRY
		BEGIN CATCH
		DECLARE @ErrNo INT,@ErrMsg NVARCHAR(4000),@ErrSev INT,@ErrStt INT
		SELECT @ErrMsg = '(' + CONVERT(NVARCHAR(4000),ERROR_NUMBER()) + ') ' + ERROR_MESSAGE(),@ErrSev = ERROR_SEVERITY(),@ErrStt = ERROR_STATE()
		IF @@TRANCOUNT > 0 ROLLBACK TRAN
		RAISERROR(@ErrMsg,@ErrSev,@ErrStt)
	END CATCH
END