CREATE TABLE [AZ].[User]
(
	[VCode]						BIGINT			NOT NULL IDENTITY(1,1),
    [Username]					NVARCHAR (100)	NOT NULL,
    [Password]					NVARCHAR (100)	NOT NULL,
    [PasswordSalt]				NVARCHAR (60)	NOT NULL,
    [IsApproved]				BIT				NOT NULL,
    [IsLock]					BIT				NOT NULL,
    [LastLoginDate]				DATETIME		NULL,
    [Email]						NVARCHAR (100)	NULL,
    [CellPhone]					NVARCHAR (20)	NULL,
    [ResetPasswordCount]		TINYINT			CONSTRAINT [DC_User_PasswordResetCount] DEFAULT ((0)) NOT NULL,
    [LastResetPasswordDate]		DATETIME		NULL,
    [FailedAttemptCount]		TINYINT			CONSTRAINT [DC_User_FailedAttemptCount] DEFAULT ((0)) NOT NULL,
    [LastFailedAttemptDate]		DATETIME		NULL,
    [LastChangedCellPhoneDate]	DATETIME		NULL,
    [LastChangedEmailDate]		DATETIME		NULL,
	[Code]						VARCHAR (20)	NOT NULL,
	[IsSubscribed]				BIT				NOT NULL,
	[IsShahkarEnabled]			BIT				CONSTRAINT [DC_User_IsShahkarEnabled] DEFAULT ((1)) NOT NULL,
	[UserTypeVCode]				SMALLINT		CONSTRAINT [DC_User_UserTypeVCode] DEFAULT ((2)) NOT NULL,
	[TokenExpirationTime]		INT				CONSTRAINT [DC_User_TokenExpireTime] DEFAULT ((525600)) NOT NULL,
	[SendLinkUrlSms]			BIT				CONSTRAINT [DC_User_SendLinkUrlSms] DEFAULT (1) NOT NULL,
	[UserPaymentTypeVCode]		SMALLINT		CONSTRAINT [DC_User_UserPaymentTypeVCode] DEFAULT (1) NOT NULL,
	[Name]						NVARCHAR(1000)	NULL,
	[FirmRegistrationVCode]		BIGINT			NULL,
	[DocApproved]				TINYINT			CONSTRAINT [DC_User_DocApproved] DEFAULT (0) NOT NULL,
	[TrackingCode]				NVARCHAR(500)	NULL,
	[ShebaNumber]				NVARCHAR(100)	NULL,
	[TrackingSendLink]			BIT				CONSTRAINT [DC_User_TrackingSendLink] DEFAULT (0) NOT NULL,
	[PartnerLogoUrl]			NVARCHAR(MAX)	NULL,
	[VerificationCode]			INT				NULL,
	[VerificationExpireDate]	DATETIME		NULL,
	[VerificationCodeTryCount]	INT				NULL,
	[IdentificationLimit]       INT             CONSTRAINT [DC_User_IdentificationLimit] DEFAULT ((10000)) NOT NULL,
	[IsApiFree]                 BIT             CONSTRAINT [DC_User_IsApiFree] DEFAULT ((0)) NOT NULL,
    [SelfOtp]                   BIT             CONSTRAINT [DC_User_SelfOtp] DEFAULT ((0)) NOT NULL,
	[ApiExpirationDate]			DATETIME		NULL,
	[EntryDate]					DATETIME        CONSTRAINT [DC_User_EntryDate] DEFAULT (GETDATE()) NOT NULL,
    [LastModifiedDate]			DATETIME        CONSTRAINT [DC_User_LastModifiedDate] DEFAULT (GETDATE()) NOT NULL,
	[AvailableUserPaymentTypeVCode] SMALLINT        NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([VCode]),
	CONSTRAINT [FK_User_UserType] FOREIGN KEY ([UserTypeVCode]) REFERENCES [AZ].[UserType]([VCode])
)
